# Encoder pre-training config. Override method to swap loss: cardpol | vqvae | curl
#
# CARDPOL: python -m afr.pretrain_encoder data_config=afr/data_configs/breakout.yaml
# VQVAE:   python -m afr.pretrain_encoder data_config=... method=vqvae
# CURL:    python -m afr.pretrain_encoder data_config=... method=curl

defaults: []

hydra:
  job:
    chdir: false  # keep cwd so relative paths (data_config, data paths in YAML) work

# Path to data config YAML (environment, data, validation_data). Required override.
data_config: ???

# Run / logging
log_dir: artifacts
device: cuda:0
n_steps: 10000
batch_size: 512
no_wandb: false
group: default

# Encoder pretrain: method selects loss; method-specific params below
method: cardpol  # cardpol | vqvae | curl
method_standalone: true  # When true for vqvae/curl, disables BC/state_decoder/state_classifier

# Shared
learning_rate: 1.0e-4
classifier_learning_rate: 1.0e-4
trajectory_length: 10
log_interval: 100
save_interval: 2000
val_interval: 500
val_batch_size: 64
val_n_batches: 10

# CARDPOL (method=cardpol)
num_sources: 2
classifier_hidden_sizes: [256, 128]
classifier_combine_mode: concat

# VQVAE (method=vqvae)
vqvae_num_embeddings: 512
vqvae_commitment_cost: 0.25

# CURL (method=curl)
curl_pad: 8
curl_temperature: 0.1

# Auxiliary heads (disabled by default when method_standalone for vqvae/curl)
use_bc_head: false
use_state_decoder: false
use_state_classifier: false
use_image_decoder: true
image_decoder_log_interval: 500
